Repository gitdeac/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#6 Integrar requisitos v1.0
  docs/requisitos.md
Labels: Analise

#8 Integrar arquitetura V1.0
  docs/arquitetura.md
Labels: Arquitetura

#10 Integrar implementação V1.0
  src/jogovelha.py
Labels: Programação

#12 Integrar testes V1.0
  src/teste_inic.py
Labels: Teste

#13 Gerar release V1.0
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/teste_inic.py
Labels: Operações
